name: Testing

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: installing packages
      run: npm ci
    - name: running tests
      run: npm run test
    - name: building
      run: npm run build

